apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vic-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/october-2025-jobs/ArgoCD-nov-jobs-again.git
    targetRevision: HEAD
    path: argocd-app-configurations/prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: vic-namespace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

      
