# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: myapp-etech
# spec:
#   selector:
#     matchLabels:
#       app: myapp
#   replicas: 4
#   template:
#     metadata:
#       labels:
#         app: myapp
#     spec:
#       containers:
#       - name: myapp
#         image: rudolphnfor/etechapp
#         ports:
#         - containerPort: 8080




apiVersion: apps/v1
kind: Deployment
metadata:
  name: vic-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: vic-container
        image: nginx:latest
        ports:
        - containerPort: 80
