apiVersion: apps/v1
kind: Deployment
metadata:
  name: vic-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 17
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: vic-container
        image: nginx:latest
        ports:
        - containerPort: 80
